language: node_js

node_js:
  - "0.10"

notifications:
  - hipchat: 6dc94c09cb45ab66a7f0dc680954a3@Triperna-V3

before_install:
  - npm install -g gulp
  - npm install -g bower

install:
  - npm install
  - bower cache clean
  - bower install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp all